version: '3'
services:
  traefik:
      image: traefik:v1.7-alpine
      logging:
        options:
          max-size: "50m"
          max-file: "3"
      command: >
        --logLevel='INFO'
        --web
        --InsecureSkipVerify=true
        --defaultentrypoints=https,http
        --entryPoints='Name:http Address::80'
        --entryPoints='Name:https Address::443 TLS Redirect.EntryPoint:http'
        --retry
        --docker
        --docker.endpoint='unix:///var/run/docker.sock'
        --docker.exposedbydefault=true
        --docker.watch=true
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:localhost"
        - "traefik.protocol=http"
      networks:
        - docker_net
        
  app:
    image: php:8.1-fpm
    volumes:
      - ./new-laravel:/var/www/html
    working_dir: /var/www/html
    networks:
      - docker_net
    depends_on:
      - mysqldb
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./new-laravel:/var/www/html
    depends_on:
      - app
    networks:
      - docker_net

  mysqldb:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: changemeplease
    networks:
      - docker_net
    ports:
      - "127.0.0.1:3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: changemeplease
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:admin.localhost"
      - "traefik.protocol=http"
    networks:
      - docker_net
    ports:
      - "127.0.0.1:8080:80"

networks:
  docker_net:    
    driver: bridge
